version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./src/:/var/www/html/"
    ports:
      - "9000:80"
    command: [ "./start.sh" ]
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3300:3306"
    volumes:
      - ./docker/MYSQLDATA:/var/lib/mysql
      - ./configs/init-db.sql:/docker-entrypoint-initdb.d/1.sql